# Generated by Django 5.1.7 on 2025-04-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Военное подразделение',
                'verbose_name_plural': 'Военные подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('formed', 'Сформирована'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Имя заказчика')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон заказчика')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('title', models.CharField(verbose_name='Округ', max_length=50, choices=[('Leningrad Military District', 'Ленинградский военный округ'),('Moscow Military District', 'Московский военный округ'),('Central Military District', 'Центральный военный округ'),('Southern Military District', 'Южный военный округ '),('Eastern Military District', 'Восточный Военный округ'),('None', 'Нет')], default='None'))],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='Тип услуги')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='military.division', verbose_name='Подразделение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Связь заявки и подразделения',
                'verbose_name_plural': 'Связи заявок и подразделений',
                'unique_together': {('order', 'division')},
            },
        ),
    ]
