# Generated by Django 5.1.7 on 2025-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
